name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  ECR_REGISTRY_URI: "634441478571.dkr.ecr.ap-south-1.amazonaws.com/demo-app"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build Express app
        run: npm run build
      - name: Push Docker Image to ECR
        run: sudo docker build -t $ECR_REGISTRY_URI:${{ github.sha }} .
      - name: Push Docker image to ECR
        run: |
          aws configure
          aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin $ECR_REGISTRY_URI
          sudo docker push $ECR_REGISTRY_URI:${{ github.sha }}
      - name: Create Infra
        run: |
          terraform init
          terraform plan
          terraform apply
